name: Scrapper Schedule

on:
  schedule:
    - cron: '0 7 * * 1'  # Every Monday at 07:00 UTC
  workflow_dispatch:     # Optional manual run from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Or whatever Python version you use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scrapper/requirements.txt

      - name: Run the scraper
        run: python scrapper/main.py
